[package]
name = "RustSA"
version = "0.1.0"
authors = ["Imran Khaliq-Baporia <imran.khaliq@berkeley.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust-gmp = "0.5.0"
